#!/bin/sh

PREFIX="pre-commit:"

cd ./src/client/
echo "$PREFIX Execute client lint-staged"
if ! npx --no-install lint-staged; then
    exit 1
fi

cd ../extension/
echo "$PREFIX Execute extension lint-staged"
if ! npx --no-install lint-staged; then
    exit 1
fi